[project]
name = "shiny-hunt"
version = "0.1.0"
description = "Automated shiny Pokemon hunting"
requires-python = ">=3.11"
dependencies = [
    "opencv-python",
    "numpy",
    "PySide6",
    "PySide6_Addons",
    "PySide6_Essentials",
    "shiboken6"
]

[project.scripts]
shiny-hunt = "shiny_hunt.main:main"